# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9de493f538fdb8604126d14535a0834da10c3b80d5977e7cd11b898b68548984618f89d5706df19037fb64a0b1fd8cb6d5285876a1c4b766d72723ce4173bcc7

test:
  secret_key_base: 4e9cbb2c80d4d7f6c01e4c1ecd38c3433d20c9d224158e8884ae1abe7c2c520da2fda3ece2f9141217a7c37b49771ba28549dca88986d0975c9e0e55ade64241

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
